<?php
//$node = \Drupal::routeMatch()->getParameter('node');

function my_news_menu()
{
  $items = array();
  $items['mynews'] = array(
    'title' => t('My News'),
    'page callback' => 'my_news_list',
    'access arguments' => array('access content'),
  );
  return $items;
}

function my_news_list()
{

  //  return t('Hello World');
    $query = new EntityFieldQuery();
    $query -> entityCondition('entity_type','node')
      ->propertyCondition('status', NODE_PUBLISHED)
      ->propertyOrderBy('created', 'DESC')
      ->range(0,10);
//    $query->entityCondition('entity_type', 'node')
//          ->entityCondition('bundle', 'news')
//          ->propertyCondition('status', NODE_PUBLISHED)
//          ->propertyOrderBy('created', 'DESC')
//          ->range(0, 10);

       $result = $query->execute();


    if (isset($result['node'])) {
      $news_items_nids = array_keys($result['node']);
      $news_items = entity_load('node', $news_items_nids);
    }


        $output = "<ul>\n";

          foreach ((array)$news_items as $news_item)
              {
                $snippet = "<li>\n";
                $snippet .= "<h2><a href='/node/".$news_item->nid."'>".t($news_item->title)."</a></h2>\n";
                $snippet .= "<p>".t(substr($news_item->body['und'][0]['value'],0,600))."</p>\n";
                $snippet .= "</li>\n";
                $output .= $snippet;
              }
        $output .= "</ul>\n";

  return $output;
}

//echo "ceci se trouve dans le my_news_block.module";
